name = "AWR - Advanced Wound Reaction";
description = "Advanced Wound Reaction";
tooltip = "Advanced Wound Reaction";
overview = "Extension for ACE3's medical system. Adds more reactions when dealing with injuries.";
author = "[79AD] S. Spartan";
logo = "AWR_logo.paa";
logoOver = "AWR_logo.paa";
actionName = "GitHub";
action = "https://github.com/Spartan190/Adv_Wound_Reaction";
